# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ounce' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ounce
#
  pod 'Alamofire', '~> 4.8.2'
  pod 'Gedatsu', configuration: %w(Debug)
  pod 'Kingfisher'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftKeychainWrapper'
  pod 'Then'
  pod 'YPImagePicker'  
  pod 'UPCarouselFlowLayout'
  pod 'DropDown'
  pod 'CHIPageControl', '~> 0.1.3'


end
